config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'

get 'cont', to: 'messages#new', as: 'cont'
  post 'cont', to: 'messages#create'

 
  

  

  resources :reports, :counterandcustoms, :source_reports, 
            :requestfordemos, :contact_us,  :import_files,
             :loginpage, :export_file, :uploads, :library_accounts,
             :reports_masters, :accounts, :platforms, :faqs, :about, :sessions,
             :account_platforms, :platform_reports, :account_platform_reports

   
  get 'users/page'

 
  root 'users#index'
  get 'users/example'

 

  resources :users do
    resources :microposts
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/account.rb
class Account < ActiveRecord::Base
has_many :account_platform
has_many :platform , :through => :account_platform
end

app/models/account_platform.rb
class AccountPlatform < ActiveRecord::Base
belongs_to :account
belongs_to :platform
has_many :account_platform_report
has_many :platform_report, :through => :account_platform_report
end

app/models/contact_u.rb
class ContactU < ApplicationRecord
end

app/models/import_file.rb
class ImportFile < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
	
	validates :subject, presence: true
	validates :query, presence: true
	validates :msg, presence: true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
    default_scope -> { order(created_at: :desc) }
  validates :user_id , :presence => true
  validates :content , :presence => true, length: { maximum: 150 }
end

app/models/platform.rb
class Platform < ActiveRecord::Base
has_many :account_platform
has_many :account , :through => :account_platform
has_many :platform_report
has_many :report , :through => :platform_report
end

app/models/platform_report.rb
class PlatformReport < ApplicationRecord
belongs_to :platform
belongs_to :report
has_many :account_platform_report
has_many :account_platform , :through => :account_platform_report
end

app/models/report.rb
class Report < ApplicationRecord
has_many :platform_report
has_many :platform , :through => :platform_report

end

app/models/requestfordemo.rb
class Requestfordemo < ApplicationRecord
end

app/models/source_report.rb
class SourceReport < ApplicationRecord

end

app/models/upload.rb
class Upload < ApplicationRecord
mount_uploader :attachment, AttachmentUploader
	validates :name,presence: true
end

app/models/user.rb
class User < ApplicationRecord
has_secure_password
has_many :Microposts
validates :name , :presence => true ,:length => {:minimum => 4}
validates :password ,:presence => true ,:length => {:minimum => 4}


def self.ex(tabs)
	binding.pry
	@tab=User.where(:email => "kanchan@gmail.com")
	@tab= @tab.to_a
end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.all
  end

  def new
    binding.pry
    @report = Report.new
  end

  def show
  end

  def create
    binding.pry
    @report = Report.new(report_params)
    if @report.save
      redirect_to reports_path
    else
      render 'new'      
    end
  end

  def destroy
    @report.destroy
    redirect_to reports_path
  end

  def update
  end

private
def report_params
  params.require(:report).permit(:name, :abbrev, :file_name, :description, :frequency, :format, :created_by, :updated_by)  
end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

def log_in(user)
		session[:user_id] = user.id
	end

	def current_user?(user)
		user == current_user
	end

	def current_user
		@current_user = @current_user || User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete
	end

	def store_location
		session[:forwarding_url]= request.original_url if request.get?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil	
	end

end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/reports/create.html.erb
<h1>Reports#create</h1>
<p>Find me in app/views/reports/create.html.erb</p>

app/views/reports/destroy.html.erb
<h1>Reports#destroy</h1>
<p>Find me in app/views/reports/destroy.html.erb</p>

app/views/reports/index.html.erb
<%= link_to "new report", new_report_path %>
<br>
<%= link_to "new platform reports", platform_reports_path %>

app/views/reports/new.html.erb
<%= form_for(:report , url: reports_path) do |f| %>

<%= binding.pry %>
<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name %>
</div>

<div class="field">
	<%= f.label :abbrev %>
	<%= f.text_field :abbrev %>
</div>

<div class="field">
	<%= f.label :file_name %>
	<%= f.text_field :file_name %>
</div>

<div class="field">
	<%= f.label :description %>
	<%= f.text_field :description %>
</div>

<div class="field">
	<%= f.label :frequency %>
	<%= f.text_field :frequency %>
</div>

<div class="field">
	<%= f.label :format %>
	<%= f.text_field :format %>
</div>

<div class="field">
	<%= f.label :created_by %>
	<%= f.text_field :created_by %>
</div>

<div class="field">
	<%= f.label :updated_by %>
	<%= f.text_field :updated_by %>
</div>

<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/reports/show.html.erb
<h1>Reports#show</h1>
<p>Find me in app/views/reports/show.html.erb</p>

app/views/reports/update.html.erb
<h1>Reports#update</h1>
<p>Find me in app/views/reports/update.html.erb</p>